name: Deploy para GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar config.js com chaves
        run: |
          echo "export const config = {" > src/scripts/config.js
          echo '  SUPABASE_URL: "https://nsacgpcnhqzxassfvuts.supabase.co",' >> src/scripts/config.js
          echo '  SUPABASE_KEY: "sb_publishable_R228vwOOokXUE9Uzrqnnqg_FwfnkXXH",' >> src/scripts/config.js
          echo "  OPENROUTER_API_KEY: \"${{ secrets.OPENROUTER_API_KEY }}\"" >> src/scripts/config.js
          echo "};" >> src/scripts/config.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
